### ISSUE TITLE
{"detail":"Failed to parse request body as JSON: EOF","status":400}

### ISSUE THREAD

**Issue by hktalent** [replicate/replicate-go#24]
<img width="951" alt="image" src="https://github.com/replicate/replicate-go/assets/18223385/600ae519-f2cb-46af-b72b-c83136f2b8dc">

```

{"input":{"img":"data:image/jpeg;base64,/9j/4A....","scale":4,"version":"v1.4"},"is_training":false,"version":"6129309904ce4debfde78de5c209bce0022af40e197e132f08be8ccce3050393"}

```

**Comment by mattt** [comment]
@hktalent It looks like Replicate's API is rejecting the request because the base64-encoded image data URI is malformed or (more likely) too large. Consider uploading your image to a URL and passing that instead.

**Comment by hktalent** [comment]
@mattt Okay, I understand. Can you give me an example of replicating a temporary image? Thank you so much

**Comment by mattt** [comment]
@hktalent You can find plenty of examples for uploading files to AWS S3 /  Cloudflare R2, services like upload.io, or to your own server using SFTP. It all depends on your particular requirements.
