### ISSUE TITLE
Add metrics fields

### ISSUE THREAD

**Issue by Flake74** [replicate/replicate-go#52]
There are missing ( https://github.com/replicate/replicate-go/blob/main/prediction.go ) metrics like input_token_count, output_token_count, total_time for some chat basic models
https://replicate.com/meta/llama-2-70b-chat?input=http&output=json

**Comment by mattt** [comment]
Hi @Flake74. Thanks for calling this out. Before per-token language models, prediction metrics didn't have much information. But now, there's a lot more.

I just opened up #53, which adds this new information.

**Comment by mattt** [comment]
This is now available in [v0.18.0](https://github.com/replicate/replicate-go/releases/tag/v0.18.0)
