### ISSUE TITLE
how to run a model without version?

### ISSUE THREAD

**Issue by cdreier** [replicate/replicate-go#75]
Or how can i find the version for example for `black-forest-labs/flux-schnell` ?

Other models have a "versions" tab, seems like this is missing here?

**Comment by AnwarChakhar** [comment]
Hi,
I was wondering about the same, having the "version must be specified" for now

**Comment by mattt** [comment]
Hi @cdreier @AnwarChakhar. Sorry for the confusion. The method you're looking for is [`CreatePredictionWithModel`](https://github.com/replicate/replicate-go/blob/972c92e610e32559c8b2587daed99290209c9e41/model.go#L169).

**Comment by cdreier** [comment]
thanks a lot, will test it and leave some feedback :+1:

**Comment by AnwarChakhar** [comment]
Thanks @mattt ! it's working perfectly on my side :)

**Comment by mattt** [comment]
Closing this as resolved. 

@cdreier Let me know if you're having any problems with this, and I'll be happy to take a look.

**Comment by oliverbenns** [comment]
This needs documenting some more as I've been fumbling around trying to find llama versions (looking for a hash), putting in other billing details, asking on Replicate's discord and further debugging for this morning.

Also the examples on the readme, the `stability-ai/sdxl` example has a version, the `incredibly-fast-whisper` example has a version but no model name? Very confusing.
