### ISSUE TITLE
How to get all models of the authorized user?

### ISSUE THREAD

**Issue by tja** [replicate/replicate-go#92]
I can create a model with `CreateModel`, I can delete a model with `DeleteModel`, I can list all public models with `ListModels`, but I was not able to list the models of the authorized user. What am I missing?

**Comment by aron** [comment]
Hi, thanks for reaching out. This functionality isn't currently supported by our API. Though I can see the value in having this information available. I'll take this back to the team for consideration as we continue to extend the API.

I'm going to close this issue at the moment as there's nothing actionable we can do in the Go client library.

If you have any follow up questions please ask.

**Comment by tja** [comment]
Thanks for the quick reply. Adding this functionality would be great! How can I track the process? Is there another GitHub issue tracker I can use?

**Comment by aron** [comment]
At the moment that would be to subscribe to the changelog at [replicate.com/changelog](https://replicate.com/changelog).
